# Week 1 Assignment
Cheryl Bowersox 
IS 605 - 1

========================================================
## Problem Set 1
$$
  A \times A^T \ne A^T \times A \forall A\\

  (1)   If A is a n X m matrix and B is a m X p martrix 
          then A \times B will result in an n X p matrix \forall A, B 
          
  \vec{u} = \begin{bmatrix}
  0.5 \\
  0.5
  \end{bmatrix}\\

  \vec{v} = \begin{bmatrix}
  3\\
  -4 \
  \end{bmatrix} \\
  
$$

### dot product
$$
\vec{u}\cdot\vec{v} = (.5)(3) + (.5)(-4)= 1.5 - 2 = -.5\\
$$

### length
$$
  length(\vec{u}) =\sqrt{0.5^2 + 0.5^2} = .70710678\\
  length(\vec{v}) =\sqrt{3^2 + -4^2} = 5
$$

### linear combination 
$$
  3\vec{u} - 2\vec{v}= \\
  (3)\begin{bmatrix}
  .5\\.5 \\
  \end{bmatrix}  - 
  (2)\begin{bmatrix}
  3\\-4\\
  \end{bmatrix} = \\
  \begin{bmatrix}
  1.5\\ 1.5\\
  \end{bmatrix}  - 
  \begin{bmatrix}
  6\\-8\\
  \end{bmatrix} = 
  \begin{bmatrix}
  7.5\\ -6.5\\
  \end{bmatrix} = \\
$$
### angle between
$$
\theta = \arccos(\frac{-.5} {\sqrt{.5}\times5})
\theta = \arccos(-0.1414214)
\theta = 1.712693
$$



========================================================
## Problem Set 2



```{r}

A <- matrix(c(2,2,1,9, 5,2,1, 12, 2, 4, -1, 7),
nrow = 3, ncol = 4, byrow = TRUE)



solvmat <- function(A,b){
  A = cbind(A, b)
  i <- 1
  j <- 1
  n <- nrow(A)
  c <- ncol(A)
  
  while (i <= n ){
    # is entire col zero
      if(all(A[,j] == 0)){
        j = j +1
      }
      
      if(A[i,j] == 0){
        #find a non-zero
        w = which(A[,j] == abs(max(A[,j])))
        #swap rows
        s <- A[w,]
        A[w,] <- A[i,]
        A[i,] <- s
      }
      
      # pivot  = 1
      p <- A[i,j] # pivot
      A[i,] <- A[i,]/p
      
      #transform other rows
      k <- 1
      
      while (k <= n){
        if (k != i){
          A[k,] = A[k,] - A[i,] * A[k,j]
        }
        k <- k + 1
      }
    i <- i + 1
    j <- j + 1
    }
  
  X = A[,c]
  return(X)
}


A <- matrix(c(1,1,3,2,-1,5,-1,-2,4),
nrow = 3, ncol = 3, byrow = TRUE)
b <- c(1,2,6)

print("test system:")
(solvmat(A,b))
```
### a system of equations

$$ 

\begin{align}
x_1 = 1 \\
x_2 = 2\\
x_3 = 3\\
\\
2x_1 + 2x_2 + x_3 = 9\\
5x_1 + 2x_2 + x_3 = 12 \\
2x_2 + 4x_2 -1 x_3 = 7
\end{align}\\
\\
A = \begin{bmatrix}
2 & 2 & 1\\
5 & 2 & 1\\
2 & 4 & -1\end{bmatrix}\\

b = \begin{bmatrix}\\
9\\
12\\
7\end{bmatrix}
$$

### Solve System
```{r}
A <- matrix(c(2,2,1, 5,2,1, 2, 4, -1),
nrow = 3, ncol = 3, byrow = TRUE)
b <- c(9,12,7)
print("X")
(solvmat(A,b))
```